variants:
- variant: services
- variant: importer

templateDir: tomcat

files:

# Define a single file to be generated for role variant 'services'
- file: ROOT.xml
  variants:
  - services
  dir: conf/Catalina/localhost
  template: ROOT.xml.hbs
  # Allows to define speciyl validators.
  # If missing the best-match validator is picked automatically.
  validators:
  - xml

# Define a single file to be generated for role variant 'importer'
- file: ROOT.xml
  variants:
  - importer
  dir: conf/Catalina/localhost
  template: ROOT_importer.xml.hbs
  validators:
  - xml

# Define a single file to be generated for all role variants
- file: setenv.sh
  dir: bin
  template: setenv.sh.hbs
  # Default charset ist UTF-8 unless specified otherwise
  charset: ISO-8859-1

- file: setenv.bat
  dir: bin
  template: setenv.bat.hbs
  charset: ISO-8859-1
  lineEndings: windows


# Defines configuration parameters and default values
config:

  tomcat:
    path: /path/to/tomcat

  jvm:
    path: /path/to/java
    heapspace:
      min: 512m
      max: 2048m
    permgenspace:
      max: 256m

  topologyConnectors:
    - http://localhost:8080/libs/sling/topology/connector
