templateDir: webserver

files:

- file: "${tenant}_vhost.conf"
  dir: vhosts
  template: tenant_vhost.conf.hbs
  multiply: tenant
  multiplyOptions:
    roles:
    - website


# Defines configuration parameters and default values
config:
  website.hostname: host
